# Pandas
Pandas는 Series(1차원 테이블 데이터용)와 DataFrame(2차원 테이블 데이터용)이라는 강력한 데이터구조를 제공하여 테이블 형태의 데이터를 쉽게 조작하고 분석할 수 있는 필수적인 도구이다.
Pandas를 사용하면 데이터 필터링, 그룹화, 통계 계산 등 다양한 작업을 직관적이고 효율적으로 수행할 수 있다.

Pandas는 구조적 데이터 처리에 강점을 두고 있으며, Numpy는 대규모 수치 연산에서 고속 성능을 제공한다. 따라서, 데이터의 성격과 작업 목적에 따라 두 라이브러리를 함께 사용하는게 일반적이다.

# Series
- Series 생성 방법
- Series 구조 확인
- 데이터 조회
- 인덱싱 및 슬라이싱
- 데이터 추가
- Series 값 수정
- 인덱스 이름 변경 - rename( )
- 데이터 통계 및 요약
- 고윳값 확인
- 데이터 필터링 및 조건 선택
- Series의 데이터 연결 - concat( )
- 데이터 정렬
- 데이터 그룹화 및 집계

In [1]:
import pandas as pd
x = [10,20,30,40]
y = pd.Series(x)
print(y)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
x = [10,20,30,40]
y = ['a', 'b', 'c', 'd']
z = pd.Series(x, index=y)
print(z)

a    10
b    20
c    30
d    40
dtype: int64

In [3]:
x = {'apple':1, 'banana':2, 'cherry':3}
y = pd.Series(x)
print(y)

apple     1
banana    2
cherry    3
dtype: int64

In [4]:
x = pd.Series([10,20,30,40,50,60,70])

print(x.dtype)
print(x.index)
print(x.values) # Numpy 배열로 반환

print(x.head()) # 상위 5개 출력
print(x.tail(2)) # 하위 2개 출력 (기본값=5)

int64
RangeIndex(start=0, stop=7, step=1)
[10 20 30 40 50 60 70]
0    10
1    20
2    30
3    40
4    50
dtype: int64
5    60
6    70
dtype: int64

In [5]:
# 인덱싱 및 슬라이싱 (iloc & loc)
x = pd.Series([10,20,30,40,50,60,70])
# iloc(정수 위치 기반 인덱싱)
print(x.iloc[1])
print(x.iloc[1:4])
# loc(인덱스 레이블 기반 인덱싱)
y = pd.Series([10,20,30,40], index=['a','b','c','d'])
print(y.loc['b'])
print(y.loc['b':'d'])

20
1    20
2    30
3    40
dtype: int64
20
b    20
c    30
d    40
dtype: int64

In [8]:
# concat() - 데이터 추가
x = pd.Series([10,20,30], index=['a','b','c'])
y = pd.Series([40,50], index=['d','e'])

z = pd.concat([x,y])
print(z)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [9]:
x = pd.Series([10,20,30], index=['a','b','c'])
x['f']=60
print(x)

a    10
b    20
c    30
f    60
dtype: int64

In [10]:
x = pd.Series([10,20,30,40], index=['a','b','c','d'])
x['b']=25
print(x)

a    10
b    25
c    30
d    40
dtype: int64

In [11]:
x = pd.Series([10,20,30,40], index=['a','b','c','d'])
x[['a','d']] = [15,45]
print(x)

a    15
b    20
c    30
d    45
dtype: int64

In [14]:
x = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])
x[x>30] = x[x>30] + 10
# x[x>30] += 10
print(x)

a    10
b    20
c    30
d    50
e    60
dtype: int64

In [15]:
x = pd.Series([10,20,30], index=['a','b','c'])
x = x.rename({'a':'x', 'b':'y'})
print(x)

x    10
y    20
c    30
dtype: int64

In [16]:
x = pd.Series([10,20,30,40,50])

print("평균: ", x.mean())
print("합계: ", x.sum())
print("중위수: ", x.median())
print("최댓값: ", x.max())
print("최솟값: ", x.min())
print("분산: ", x.var())
print("표준편차: ", x.std())

평균:  30.0
합계:  150
중위수:  30.0
최댓값:  50
최솟값:  10
분산:  250.0
표준편차:  15.811388300841896

In [17]:
print(x.describe())

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [20]:
x = pd.Series(['a','b','c','b','a'])
print(x.value_counts()) # 빈도수 확인
print(x.value_counts(normalize=True)) # 빈도 비율 확인

a    2
b    2
c    1
Name: count, dtype: int64
a    0.4
b    0.4
c    0.2
Name: proportion, dtype: float64

In [25]:
# 데이터 필터링
x = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])
print(x[x>25])
print("AND 조건 필터링 결과:")
print(x[(x>25)&(x<35)])
print("OR 조건 필터링 결과:")
print(x[(x<25)|(x>35)])

c    30
d    40
e    50
dtype: int64
AND 조건 필터링 결과:
c    30
dtype: int64
OR 조건 필터링 결과:
a    10
b    20
d    40
e    50
dtype: int64

In [27]:
# 1. sort_values() 를 사용한 값 기준 정렬
x = pd.Series([20,10,40,30], index=['a','b','c','d'])
print(x.sort_values()) # 기본 값: 오름차순
print(x.sort_values(ascending=False)) # 기본 값: 내림차순

b    10
a    20
d    30
c    40
dtype: int64
c    40
d    30
a    20
b    10
dtype: int64

In [28]:
# 2. sort_index() 를 사용한 인덱스 기준 정렬
x = pd.Series([20,10,40,30], index=['a','b','c','d'])
print(x.sort_index()) # 기본 값: 오름차순
print(x.sort_index(ascending=False)) # 기본 값: 내림차순

a    20
b    10
c    40
d    30
dtype: int64
d    30
c    40
b    10
a    20
dtype: int64

In [32]:
# 데이터 그룹화 및 집계 (groupby & agg)
x = pd.Series([10,20,30,10,20,30], index=['a','b','a','b','a','b'])

print(x.groupby(level=0).sum()) # level=0은 가장 바깥쪽 인덱스를 의미
print(x.groupby(level=0).mean())
print(x.groupby(level=0).agg(['sum','mean','count']))

a    60
b    60
dtype: int64
a    20.0
b    20.0
dtype: float64
   sum  mean  count
a   60  20.0      3
b   60  20.0      3

# DataFrame
- DataFrame 생성 방법
- DataFrame 구조 확인
- 데이터 조회
- 인덱싱 및 슬라이싱
- 데이터 추가
- DataFrame 값 수정
- 열 이름 변경
- 데이터 통계 및 요약
- 고윳값 확인
- 데이터 필터링 및 조건 선택 - 다중 조건 필터링
- 데이터 병합 및 결합
- 데이터 정렬
- 데이터 그룹화 및 집계

In [33]:
x = [
    ['Ant',25,'Seoul'],
    ['Bee',30,'Busan'],
    ['Cat',35, 'Incheon']
]

df = pd.DataFrame(x, columns=['Name', 'Age', 'City'])
print(df)

  Name  Age     City
0  Ant   25    Seoul
1  Bee   30    Busan
2  Cat   35  Incheon

In [34]:
x = {
    'Name':['Ant','Bee','Cat'],
    'Age':[25,30,35],
    'City':['Seoul', 'Busan', 'Incheon']
}

df = pd.DataFrame(x)
print(df)

  Name  Age     City
0  Ant   25    Seoul
1  Bee   30    Busan
2  Cat   35  Incheon

In [ ]:
df.shape
df.columns
df.index
df.info()
df.head()
df.tail()

In [43]:
x = {
    'Name':['Ant','Bee','Cat', 'Dog'],
    'Age':[25,30,35,40],
    'City':['Seoul', 'Busan', 'Incheon', 'Daejeon'],
}

df = pd.DataFrame(x, index=['A', 'B', 'C', 'D'])
print(df)

  Name  Age     City
A  Ant   25    Seoul
B  Bee   30    Busan
C  Cat   35  Incheon
D  Dog   40  Daejeon

In [44]:
# iloc(정수 위치 기반 인덱싱)
print(df.iloc[1,2]) # 1행 2열
print(df.iloc[1:2, 0:2]) # 1행의 0,1열

Busan
  Name  Age
B  Bee   30

In [45]:
# loc(인덱스 레이블 기반 인덱싱)
print(df.loc['A', 'City']) # A행의 City열
print(df.loc['A':'B', 'Name':'Age']) # A,B행의 Name~Age열

Seoul
  Name  Age
A  Ant   25
B  Bee   30

In [47]:
df = df.assign(Cost=[10,30,150,150]) # df.assign() - 새로운 열 추가
print(df)

  Name  Age     City  Cost
A  Ant   25    Seoul    10
B  Bee   30    Busan    30
C  Cat   35  Incheon   150
D  Dog   40  Daejeon   150

In [48]:
# 열 추가 및 수정
df['Needs'] = [5,20,60,63]
df['Age'] = [20,25,30,40]
print(df)

  Name  Age     City  Cost  Needs
A  Ant   20    Seoul    10      5
B  Bee   25    Busan    30     20
C  Cat   30  Incheon   150     60
D  Dog   40  Daejeon   150     63

In [50]:
df.loc['A', 'Needs'] = 10
print(df)

  Name  Age     City  Cost  Needs
A  Ant   20    Seoul    10     10
B  Bee   25    Busan    30     20
C  Cat   30  Incheon   150     60
D  Dog   40  Daejeon   150     63

In [51]:
df.iloc[1,3] = 50
print(df)

  Name  Age     City  Cost  Needs
A  Ant   20    Seoul    10     10
B  Bee   25    Busan    50     20
C  Cat   30  Incheon   150     60
D  Dog   40  Daejeon   150     63

In [53]:
df.loc[['A','C'], 'Cost'] = 20,100
print(df)

  Name  Age     City  Cost  Needs
A  Ant   20    Seoul    20     10
B  Bee   25    Busan    50     20
C  Cat   30  Incheon   100     60
D  Dog   40  Daejeon   150     63

In [54]:
df.loc[df['Cost']>=100, 'Passed'] = True
print(df)

  Name  Age     City  Cost  Needs Passed
A  Ant   20    Seoul    20     10    NaN
B  Bee   25    Busan    50     20    NaN
C  Cat   30  Incheon   100     60   True
D  Dog   40  Daejeon   150     63   True

In [55]:
df.loc[(df['Age']>20) & (df['Name']=='Bee'), 'Needs'] = 40
print(df)

  Name  Age     City  Cost  Needs Passed
A  Ant   20    Seoul    20     10    NaN
B  Bee   25    Busan    50     40    NaN
C  Cat   30  Incheon   100     60   True
D  Dog   40  Daejeon   150     63   True

In [56]:
df = df.rename(columns={'Name':'Full Name', 'City':'Location'})
print(df)

  Full Name  Age Location  Cost  Needs Passed
A       Ant   20    Seoul    20     10    NaN
B       Bee   25    Busan    50     40    NaN
C       Cat   30  Incheon   100     60   True
D       Dog   40  Daejeon   150     63   True

In [57]:
df = pd.DataFrame({
    'Math':[85,90,95,100,80],
    'Science':[88,92,85,89,94]
})
print(df.describe())

             Math    Science
count    5.000000   5.000000
mean    90.000000  89.600000
std      7.905694   3.507136
min     80.000000  85.000000
25%     85.000000  88.000000
50%     90.000000  89.000000
75%     95.000000  92.000000
max    100.000000  94.000000

In [58]:
math_mean = df['Math'].mean()
science_sum = df['Science'].sum()

print(f"Math 평균: {math_mean}")
print("Science 합계: ", science_sum)

Math 평균: 90.0
Science 합계:  448

In [2]:
# 빈도 수 확인
import pandas as pd
df = pd.DataFrame({
    'Fruit':['apple','banana','apple','orange','banana','apple'],
    'Color':['red','yellow','red','orange','yellow','red']
})

print(df['Fruit'].value_counts())
print(df.apply(pd.Series.value_counts))

Fruit
apple     3
banana    2
orange    1
Name: count, dtype: int64
        Fruit  Color
apple     3.0    NaN
banana    2.0    NaN
orange    1.0    1.0
red       NaN    3.0
yellow    NaN    2.0

In [5]:
for col in df.columns:
    print(f"'{col}' 열의 고윳값 빈도: ")
    print(df[col].value_counts(), '\n')

'Fruit' 열의 고윳값 빈도:
Fruit
apple     3
banana    2
orange    1
Name: count, dtype: int64

'Color' 열의 고윳값 빈도:
Color
red       3
yellow    2
orange    1
Name: count, dtype: int64

In [7]:
df1 = pd.DataFrame({
    'ID':[1,2,3],
    'Name':['Ant','Bee','Cat']
})
df2 = pd.DataFrame({
    'ID':[2,3,4],
    'Score':[88,92,85]
})
display(df1, df2)

   ID Name
0   1  Ant
1   2  Bee
2   3  Cat

   ID  Score
0   2     88
1   3     92
2   4     85

In [8]:
# 데이터 병합 및 결합
# merge(df1, df2, on='target col', how='결합 방식')
# 결합방식: inner, outer, left, right
merged_inner = pd.merge(df1,df2,on='ID',how='inner')
merged_left = pd.merge(df1,df2,on='ID',how='left')
print(merged_inner)
print(merged_left)

   ID Name  Score
0   2  Bee     88
1   3  Cat     92
   ID Name  Score
0   1  Ant    NaN
1   2  Bee   88.0
2   3  Cat   92.0

In [9]:
# 데이터 결합 - pd.concat()
# axis=0 : 행 방향, axis=1 : 열 방향
print(pd.concat([df1,df2], axis=0))
print(pd.concat([df1,df2], axis=1))

   ID Name  Score
0   1  Ant    NaN
1   2  Bee    NaN
2   3  Cat    NaN
0   2  NaN   88.0
1   3  NaN   92.0
2   4  NaN   85.0
   ID Name  ID  Score
0   1  Ant   2     88
1   2  Bee   3     92
2   3  Cat   4     85

In [10]:
df1

   ID Name
0   1  Ant
1   2  Bee
2   3  Cat

In [11]:
score = pd.Series([88,92,85], index=[0,1,2])
df1['Score'] = score
df1

   ID Name  Score
0   1  Ant     88
1   2  Bee     92
2   3  Cat     85

In [ ]:
df = pd.DataFrame({
    'Name':['Ant','Bee','Cat','Dog'],
    'Age':[24,27,22,32],
    'Score':[88,95,85,90]
})
# 데이터 정렬
df.sort_values(by='Age') # Age 기준 오름차순 정렬
df.sort_values(by='Score', ascending=False) # Score 기준 내림차순 정렬
df.sort_values(by=['Age', 'Score'], ascending=[True, False]) # Age 기준 오름차순, Score 내림차순 정렬
df.sort_index() # 행 인덱스 기준 오름차순 정렬
df.sort_index(axis=1, ascending=False) # 열 인덱스 기준 내림차순 정렬

In [14]:
df = pd.DataFrame({
    'Category':['A','A','B','B','A','B'],
    'Type':['X','Y','X','Y','X','Y'],
    'Values':[10,20,30,40,50,60]
})

# 데이터 그룹화 및 집계
print(df.groupby('Category')['Values'].sum())
print(df.groupby(['Category','Type'])['Values'].mean())
print(df.groupby('Category')['Values'].agg(['sum','mean','count']))

Category
A     80
B    130
Name: Values, dtype: int64
Category  Type
A         X       30.0
          Y       20.0
B         X       30.0
          Y       50.0
Name: Values, dtype: float64
          sum       mean  count
Category
A          80  26.666667      3
B         130  43.333333      3

## Review

In [44]:
data = pd.Series([10,20,30,40])
data

0    10
1    20
2    30
3    40
dtype: int64

In [58]:
df = pd.DataFrame({
    'Name':['Ant','Bee','Cat'],
    'Age':[24,27,22]
})
df

  Name  Age
0  Ant   24
1  Bee   27
2  Cat   22

In [59]:
print(df.loc[1]['Age'])

27

In [60]:
df[df['Age']>=25]

  Name  Age
1  Bee   27

In [61]:
df['City'] = ['Seoul','Busan','Incheon']
df

  Name  Age     City
0  Ant   24    Seoul
1  Bee   27    Busan
2  Cat   22  Incheon

In [62]:
df[(df['Age']>=25) & (df['City']=='Busan')]

  Name  Age   City
1  Bee   27  Busan

In [63]:
df.groupby('City')['Age'].mean()

City
Busan      27.0
Incheon    22.0
Seoul      24.0
Name: Age, dtype: float64

In [64]:
df.loc[(df['City']=='Seoul'), 'City'] = 'Gwangju'
df

# df['City'] = df['City'].replace('Seoul', 'Gwangju')

  Name  Age     City
0  Ant   24  Gwangju
1  Bee   27    Busan
2  Cat   22  Incheon

In [65]:
df = df.assign(Age_Group=['Young','Adult','Young'])
df

# df['Age Group'] = df['Age'].apply(lambda x: 'Adult' if x >= 25 else 'Young')

  Name  Age     City Age_Group
0  Ant   24  Gwangju     Young
1  Bee   27    Busan     Adult
2  Cat   22  Incheon     Young

In [66]:
df.loc[3] = ['Dog', 29, 'Busan', 'Adult']
df

# new_row = pd.DataFrame([{'Name': 'Dog', 'Age': 29, 'City': 'Busan', 'Age_Group': 'Adult'}])
# df = pd.concat([df, new_row], ignore_index=True)

  Name  Age     City Age_Group
0  Ant   24  Gwangju     Young
1  Bee   27    Busan     Adult
2  Cat   22  Incheon     Young
3  Dog   29    Busan     Adult

In [67]:
df.groupby('City')['Age'].agg(['sum','mean'])

         sum  mean
City
Busan     56  28.0
Gwangju   24  24.0
Incheon   22  22.0